# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CalorieCalculatorDesign_Grams.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 141)
        self.header = QtWidgets.QLabel(Form)
        self.header.setGeometry(QtCore.QRect(0, 10, 401, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.header.setFont(font)
        self.header.setAlignment(QtCore.Qt.AlignCenter)
        self.header.setObjectName("header")
        self.inputGrams = QtWidgets.QLineEdit(Form)
        self.inputGrams.setGeometry(QtCore.QRect(130, 50, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputGrams.setFont(font)
        self.inputGrams.setText("")
        self.inputGrams.setObjectName("inputGrams")
        self.buttonReady = QtWidgets.QPushButton(Form)
        self.buttonReady.setGeometry(QtCore.QRect(130, 100, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonReady.setFont(font)
        self.buttonReady.setObjectName("buttonReady")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.header.setText(_translate("Form", "Ile gramów gramów produktu chcesz dodać?"))
        self.buttonReady.setText(_translate("Form", "Gotowe"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
